# Site Identity
title: Rex Yuan's Blog
description: Rex Yuan's writings.
url: https://jekyll.rexyuan.com
baseurl: ""

# Author Information
author:
  name: Rex Yuan
  email: hello@rexyuan.com

# Localization
lang: en-US
locale: en_US

# SEO Metadata
keywords: Rex Yuan, Blog
theme_color: "#EEEEEE"
ms_tile_color: "#00aba9"
mask_icon_color: "#5bbad5"

# Open Graph
og_type: website
og_image: /assets/images/og-image.png
og_image_type: image/png
og_image_width: 1200
og_image_height: 630
og_image_alt: "The black text Rex Yuan in Renogare"

# Social profile data
profile:
  first_name: Rex
  last_name: Yuan
  username: rexyuan
  gender: male

# Theme metadata (for footer or display)
theme_repo: "https://github.com/RexYuan/rexyuan.com-theme"
theme_license_url: "https://unlicense.org"
theme_license_name: "Unlicense"

# Permalink structure for blog posts
permalink: /:year/:month/:day/:title/

# Markdown settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: false

# Plugins — declared here only to avoid override conflicts
plugins:
  - jekyll-postfiles
  - jekyll-remote-theme

# Build settings
future: true         # Allow future-dated posts to show
show_drafts: false   # Set true if you want to see drafts locally

# Collections
collections:
  posts:
    output: true

# Default layout for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
